# Generated by Django 4.1.7 on 2023-02-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=40)),
                ('github', models.CharField(blank=True, max_length=200, null=True)),
                ('que1', models.TextField()),
                ('que2', models.TextField()),
                ('que3', models.TextField()),
                ('que4', models.TextField()),
                ('que5', models.TextField()),
            ],
        ),
    ]
